name: deploy
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: check-out
        uses: actions/checkout@v3
      - name: run-build
        env:
          REACT_APP_FIREBASE_CONFIG: '${{ secrets.REACT_APP_FIREBASE_CONFIG }}'
        run: |
          npm ci
          npm run build
      - name: run-deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MINI_PAINT_INN23 }}'
          channelId: live
          projectId: mini-paint-inn23
