name: linter-check
on:
  push:
    branches:
      - dev
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: check-out
        uses: actions/checkout@v3
      - name: run-lint
        run: |
          npm ci
          npm run lint
